language: node_js
sudo: false
node_js:
- 5.2
- 4.2
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- ./test/shell_scripts/run_tests.sh
after_success:
- cat ./build/reports/coverage/coverage.lcov | node_modules/coveralls/bin/coveralls.js
after_failure:
- for file in *.log; do echo $file; echo "======================"; cat $file; done
  || true
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: qgHH2/jcM35KN9qLFLdn4UBXCy54U8kqmCy/ami1TLbYwZ+96J1zxDaSN0erygKVk18St/FO+kAnyRpzytvFSckIWpnGH7/THdnEqeIhzrXFCSJQGiyrBqdIHshLBIi78kmws5aJxo5GT2A31ch5+N0NUBhdpfLpJwtjVPsdVkx7Xjjl+nBrdjn8+p1npgIYpOen6GJEStqLNYessd6BAa8n8sKEoKdAmi7omYtiFemUgF7kVUqPCD8xqfD0LTPZOVvgMcbGYfQz3Nmenw7EWNOs6PYWlsg5H2IJMG4HJzv1Gy/6Vy8m/90S99dMaFStrSnMqyyajb+TPUR6FKYInHk13QDcCwdTFGhIDqWVPhlehEku3sOZ4uVNxKvyRS53JwhiYdz/uT6E6Fgl11t4CXr5kNc395WoMfs4nuesl/5Mz5vg/J4gnghQUcoVawXSxuetKkY+45OXyVQqFzVZAzlUFThfDT2YKE7VbevasfMuLAOF8gKrqTsiOhqI4ptsH3PW1mnnDqKzQYB/zj0iYAPIQwiZlnQVbc79RLpoJ14fOVnbZsegenPSjXN5uGNwFtt9eoFC/5wYKtGUVDHEgu3W6HJz3eBogmzJq2w2y8STnP36zSrzSQGsEDqMeWqGvEZZbrXKEzHuQgeufFsdi2MfOA1/26mUcL8C4jU/BGQ=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: kPNh4Tg8CgJsxrA4ictCXj1IU1d6Q+0f7XtXBIGI9cFhYruC13nP1kT2IrTrW1OrfsHuvBg3Lb6uBAEA/oPIt1zRWhCfUXGkOwbM//ogLviMFCW+jJOsbGJ2KljTOfPQ/BWFPJH1MaxHovvgsfTkxxwIXBlsqGOiFtNBVKL+x2KitKyLMSMqd1v1mqzEZUHY97gwc7TsGUxBEt4fN84XTx0zqfJz88/fhLp5B17LHHH92PlwtD/Pg+EfLMgmTuBtz0MVMrmyDgBnqGhi2dSuNSPW1FBeWSot/MU2+j426+NfgNt+uSl6GLLlPD0MQIEjgwrSnXnsODhQ8d/dbJ5l5df6gnsbheQD+h/feqTyB3D4Bg82HdIKJpa8SXvPze1FjiSHH6ejSdmoLedSAxZYGNP40eOpW7OCme/COBCYuGuHVl02XuWBZLlNQAYdZ0Vg3PnWbJYzu/I3UyoGKxWBF5Chb7k18z57nxwN+aTy/5nCu250bqMH0xldxyrU/pFfR2pALPlhlCbvoaJTDD2HRyM8R56lXHxSgpMFZl6uxMbzltx/j1CiYcTkxEEh/v78BRSOqjVAazTcoSMrLTN27akzjPRcbjZPb9UoyKQ+LhXFngw4Wz34geGntVtKxD3OkCho9TQ6Vtmn974d9j6TyaQKBeo6UqDrPw31+92cm64=
