language: node_js
sudo: false
node_js:
- '0.12'

env:
  matrix:
    - BROWSER=chrome  BVER=stable CHROME_BIN=./browsers/bin/chrome-stable
#    - BROWSER=firefox BVER=stable FIREFOX_BIN=./browsers/bin/firefox-stable

matrix:
  fast_finish: true

before_install:
- npm install -g Financial-Times/origami-build-tools#node12
- obt install

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
- obt verify
- npm test -- --browsers $BROWSER --reporter dots

after_success:
  - cat ./build/reports/coverage/coverage.lcov | node_modules/coveralls/bin/coveralls.js

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

